apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgB2bRI6xf2iNm8ZjWJVxPsNnxA9cpDbIUP6cBqPkkgqfQx2o5fzX2OCCqmlcoU52eHSZuZYADdUawdizsFUIhooNGRpFTLWggcUpsyiBL1QyZWLGO1oSJ/7GGqpasBohQcjwg6P1DIhxqyC7Xo7n4ZFIQmELwi/YN73+6MUp+x3i/YWAMG92zvn8V0LyEMNIl6ChcGNbXVo5bhj1e5suI/NNO3Z+C4l41gkkzUY4GiXOKoJNDr9cK4+q+SAX9jJxVwHIVBI53uo9dVtXgQu0fvq3BUuws2YooLZP0ufTNHt03MJwJVuPYgTBMKY7P8luKqzXcfjDZDUOgmGJXyD550TmquGwzWUUJaaMVA9ciuqnmzwS+yqs/tEbPEVcevvYLnL8uNtIIFXybuKecvSMbBFzPQj1zlw4PO2WzCAKJy3lQOUYC9PVW9IWEfhARn18Z6W0w6CgxAOmpb74ihnz9BCzn0FsemDh69HMALsP8TFcFl9+ar5TNBI9c2eaxeKuXMPu+ShRqUJ0mS/EWkQLvs5OGHCxCovXa3oad+Wh6flLnpMmqjBlnI+TZpA6VxDfj2bOj45WPkxtwhE9kJfDtJCzL6mRamHChjjqozLuw90wDNCDlapfgySjeDeXixTIamfOB+3zyJm3vvLerwH53li9WKJTzXNbPnbPX6SN5+NZ0kEZEl4abIYU4qEoAKGLfE=
    user: AgAxLlONUdyD5ePj6xG8JTMZM/U4fydG0eiIn4qKHRiipWYxYyKE3r/sbs0XOWJMbBc7QnxsjG9IEQ95GYC3+VHdiD5nkb2sQkBRh0bzKkzYt/fIPlB5g4OoZLRFoZCp3TteeAsxulJvepIolJwy4mWMoomtpBkWv/H77/BWmRzzspoCUgJlag4vAyLHhEf61uWEpmD5BNPmJfcWoa8kZ6eF9XZtX3Xf11p+jNedlfg0TVJf1gSTgbLJAul1sIBCU8ccGfokrC5PRVjKoofAUg5kBVatFSBZ7m6hQGqiSwYT17Ia97TzvXWNjQk1MIUE08snK5EGJnJkjL8KyNksk7GZAOjHQm0zFQtIoviMYnSdUlLbWEVruDaPBwVL25H2vGwzPgie/W3TE3vxtHV4HV3eyB01BoS1/DI4E2v41gzhkmHC2Bw4tCPHbLgd6i0niTNcOvL60LyMDHUZ4tsNHbn7/FJunW44orRCkIRttLap/tp7zPYGNRZbOu8U5RR6FBX4bNb8q16rfHEHpSRSxUnlP3vdUsyWaYl+d/x9+WxwMBiqpT0oXXpR4enKNLQ4Ca39KOyvd/Fnz+fFQs4/8hqe6Af6gkQ1yPd17tV40PRs0G1+SzYNUudg4pYrn+HGAFVcFtECzHg8DPtPN6a0N/fDuoU/cZnCQIhWtXDpQAtDiSwBQmzve8wwAGkwmDct6C4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
