apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBnXvH+VZ7Sk3xH1i9f1QlDYD91w2jpLmMoVScqSimEy3uPfDdTQ/49J1OHX9XUJs10SjDgmaipd/sRB0bkSTUyO7JlVIBd69y8RlQ6qJTrMeDJZcn5QkC+vGkfBmu+F31N2mTUWhzRDJo78aN7yA3aNrFmkvW/Ma/fntf8dbUAY+uOEbWacrKkEIAZXfIeA/eFSLSz20cBd3iIY6iaXqQepnVodoR4dHaev2Urwi+OlkVuYYuFOT3d0YQNoT+IKkJjD0LGatxezm+v9U9EscuoH1tBDhf6iSGPgpFyDWq+sCRoc9S0dFydCLS9yAAe+7xDV4+WmePbyMMr2Tic54u5qF+0IPb2EsC9YTdIeaeHmP4QnFboVDOe6BPNjfXYqwp+pwkvrFdHF8q+tAwTkesI1iamQEphVNfz6KcWo6rYIIoWZPstATXgEO1OjTnBRQIiLncD3qCJClsIlpyYyGrfqKQCo/nmV4gFMU7o9CHxNPJAnivgFyecdCoVeWura7MAvindBEuTMGxlb/QM2uolWiFyZqBrS67taoGTT8cAvNURB6JuiQv06gZaE1R7Yvp2cudkYB8iT718zEghV2oM3XubDXCiaTvxvBp62bNT7zyPddcLVenztMt8w68vIv5epm0OPQY7+Er0KlojUWh9STasTsZ2LAFbN0+llpOXr5VS8ffy9aov50dcIUCHV/Vh+euOf/WlhUA=
    user: AgDTeHWlAv+1pbhbMAWyCnmtyEt7sxNkgnlCTGx/UV6qySCQR/fwop74GrSE7uvfMP6KNHx4PKKdOSonI0TyAT2o3aGh8HuY65Kary3+3R6yxeP7KSFmLQonLk16p5zK36DC49SDUQ2/laLR9BArX9wHGhhveOXI7zU9KC9CGykRu6de/z56l55f3WMZB/cnL7tEOa21539sI+hV2VSPUTJHWrWPaBU8VbJiTXnfBBEMOiHmZnspxlqBtKQlJj3jc4pGgRLOYfGZkKN+PyUQDb4j0lMtpXazQLYlhdBaiMtLzn3LxRgDEmkf3DBX7b0g0XIVtZhlLVa47isJmVgnhrL0fFB/6IbwaroA1g8C78VLLrx4kGvgIKL6npdLYwa71h9Vp7uyzGV9WL3DiJsBqy8d/AzxxcjhaxYFk5YHxP/rUnW6EOdB/RYmK6YnqMFDuz9wtFF35V/kuVHynZg0ohgYosdsOWEilq9UfO/ytR6evoAyWcR3MsDrtdi+3wCQV172LByfQNpdKnBv95h4zNQ6yyZkmuY2e9UGyEy5O0LvE7ian0jxo1TkIiRuej9eXTr9SNWZpAFuOUyzz44TV39QTRsXeVbcI8Xa72k5Ftv10swbuKEcbwAR0U1DI0zrmQiJNjPeHSHhFc/lpHvq/2GTh32glGyaPCNO8xaF93qR2wSRaLWFGSsa09p/rydZe2yAsY8rGA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
